config-version: 2
message: The message you sent had blocked words written
words:
  word1:
    severity: 1
  word2:
    severity: 2
  word3:
    severity: 3
  word4:
    severity: 4
  word5:
    severity: 5

severity-actions:
  severity-1:
    - "msg $player Hey! We dont say '$term' around here!"
    - "log $player has used a severity-1 word '$term'"
  severity-2:
    - "kick $player Hey! We dont say '$term' around here!"
    - "log $player has used a severity-2 word '$term' "


messages:
  default: Your message was not sent due to inappropriate content.
substitutions:
  '1': i,l
  '4': a
  '8': b
  '3': e
  '0': o
  '5': s
  '7': t
  v: u
  '9': g
  '2': z
  (: c
  /: y
  vv: w
  '%': x
  '!': i
  '+': t
  '$': s
  '|': l,i
