# PLEASE DO NOT CHANGE THIS!!!!!!
# This is used to make sure you are using the most up to date config version.
config-version: 2

# The message sent when a player is filtered
message: 'The message you sent had blocked words written'

# Words to be censored
# Put in as lowercase, as messages are translated to lowercase
# before being checked. :P

words:
  "word1":
    severity: 1
  "word2":
    severity: 2
  "word3":
    severity: 3
  "word4":
    severity: 4
  "word5":
    severity: 5

severity-actions:
  severity-1: "msg $player 1 $term"
  severity-2: "msg $player 2 $term"
  severity-3: "msg $player 3 $term"
  severity-4: "msg $player 4 $term"
  severity-5: "kick $player Please refrain from saying '$term'"

messages:
  default: "Your message was not sent due to inappropriate content."